not_know1 = "\,/(^_^)\,/"
cool_guy = "ヾ(⌐■_■)ノ"
dead_sm = "[✖‿✖]"
classic = "(͡° ͜ʖ͡°)"
classic_mustache = "(͡°╭͜ʖ╮͡°)"
wtf_smile = "( ͡⊙ ͜ʖ͡⊙)"
weapon = "▄︻̷̿┻̿═━一"
not_know2 = "¯\_(ツ)_/¯"
panda = "ʕ•ᴥ•ʔ"
fighter = "(ง ͠° ͟ل͜ ͡°)ง"
pretty = "(づ｡◕‿‿◕｡)づ"
classic_with_money = "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]"
crying = "(ಥ﹏ಥ)"
kissing = "(づ￣ ³￣)づ"
fin_and_jake = "|(•◡•)| (❍ᴥ❍ʋ)"
spider = "ᄽὁȍ̪ őὀᄿ"
fear = "〣(ºΔº)〣"

